apiVersion: v1
kind: Pod
metadata:
  name: nodeappmanthan
  labels:
    app: nodeappmanthan
spec:
  containers:
    - name: nodeapp
      image: manthanrapyder/nodeappdemo:tagVersion
      ports:
        - containerPort: 8080
